apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_USERNAME: "${MYSQL_USER}"
  DB_PASSWORD: "${MYSQL_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
  GEMINI_API_KEY: "${GEMINI_API_KEY}"
