apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
