name: Ticket
description: 버그 리포트 또는 기능 제안
labels: ["status:new"]
body:
  - type: dropdown
    id: type
    attributes:
      label: 타입
      options:
        - Bug
        - Feature
        - Improvement
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options:
        - High
        - Low
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: 설명
      placeholder: 문제 또는 기능 설명
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 기대 동작
      placeholder: 어떻게 동작해야 하는지
    validations:
      required: false
