apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ${WORKER_IMAGE}
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/firebase/service-account.json
          envFrom:
            - configMapRef:
                name: worker-config
            - secretRef:
                name: worker-secret
          volumeMounts:
            - name: firebase-credentials
              mountPath: /var/secrets/firebase
              readOnly: true
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            periodSeconds: 30
            failureThreshold: 3
      volumes:
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials
