apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch
  template:
    metadata:
      labels:
        app: batch
    spec:
      containers:
        - name: batch
          image: ${BATCH_IMAGE}
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: batch-config
            - secretRef:
                name: batch-secret
