apiVersion: v1
kind: Secret
metadata:
  name: batch-secret
type: Opaque
stringData:
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  GEMINI_API_KEY: "${GEMINI_API_KEY}"
  YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
  SENTRY_DSN_BATCH: "${SENTRY_DSN_BATCH}"
  SENTRY_ENVIRONMENT: "${SENTRY_ENVIRONMENT}"
  SENTRY_RELEASE: "${SENTRY_RELEASE}"
