apiVersion: v1
kind: Secret
metadata:
  name: admin-api-secret
type: Opaque
stringData:
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
  ADMIN_PASSWORD_SHA256: "${ADMIN_PASSWORD_SHA256}"
  ADMIN_TOKEN_SECRET: "${ADMIN_TOKEN_SECRET}"
